#!/usr/bin/env python3
"""Bridge usd-simready-inspector assets into NVIDIA Content Agents Physics Agent."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
from pathlib import Path
from typing import Optional


DEFAULT_CONTENT_AGENTS_ROOT = Path.home() / "content-agents"
DEFAULT_PHYSICS_AGENT = DEFAULT_CONTENT_AGENTS_ROOT / ".venv" / "bin" / "physics-agent"


def _safe_session_id(value: str) -> str:
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._-")
    return stem or "asset"


def _load_lightbulb_template(content_agents_root: Path) -> dict:
    import yaml

    template_path = content_agents_root / "apps" / "physics_agent" / "configs" / "lightbulb.yaml"
    with template_path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def _set_renderer_backend(config: dict, backend: str) -> None:
    steps = config.setdefault("steps", {})
    for step_name in ("identify_asset", "build_dataset_usd"):
        step = steps.setdefault(step_name, {})
        renderer = step.setdefault("renderer", {})
        renderer["backend"] = backend


def _set_vlm(config: dict, backend: Optional[str], model: Optional[str]) -> None:
    if not backend and not model:
        return
    predict = config.setdefault("steps", {}).setdefault("predict", {})
    vlm = predict.setdefault("vlm", {})
    if backend:
        vlm["backend"] = backend
    if model:
        vlm["model"] = model


def _write_config(
    input_usd: Path,
    output_dir: Path,
    content_agents_root: Path,
    render_backend: str,
    vlm_backend: Optional[str],
    vlm_model: Optional[str],
    collision_approx: str,
) -> Path:
    config = _load_lightbulb_template(content_agents_root)
    session_id = _safe_session_id(input_usd.stem)
    working_dir = output_dir / f"{session_id}_physics_agent"

    config["project"] = {
        "name": f"{session_id}_physics_agent",
        "description": "Generated by usd-simready-inspector for Content Agents Physics Agent.",
        "session_id": session_id,
        "working_dir": str(working_dir.resolve()),
    }
    config["input"] = {
        "usd_path": str(input_usd.resolve()),
        "reference_images": [],
    }
    _set_renderer_backend(config, render_backend)
    _set_vlm(config, vlm_backend, vlm_model)
    config.setdefault("steps", {}).setdefault("apply_physics", {})["collision_approx"] = collision_approx

    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / f"{session_id}.physics_agent.yaml"
    import yaml

    with config_path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(config, handle, sort_keys=False)
    return config_path


def _expected_outputs(input_usd: Path, output_dir: Path) -> dict[str, str]:
    session_id = _safe_session_id(input_usd.stem)
    working_dir = output_dir / f"{session_id}_physics_agent"
    return {
        "working_dir": str(working_dir),
        "predictions_jsonl": str(working_dir / "predictions" / "predictions.jsonl"),
        "report_html": str(working_dir / "predictions" / "report.html"),
        "physics_usd": str(working_dir / "physics" / f"{input_usd.stem}_physics.usda"),
    }


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate and run a NVIDIA Content Agents Physics Agent config for a USD asset.",
    )
    parser.add_argument("input_usd", type=Path, help="Input USD/USDA/USDC/USDZ asset")
    parser.add_argument("--output-dir", type=Path, default=Path("out/content_physics"))
    parser.add_argument("--content-agents-root", type=Path, default=DEFAULT_CONTENT_AGENTS_ROOT)
    parser.add_argument("--physics-agent", type=Path, default=DEFAULT_PHYSICS_AGENT)
    parser.add_argument("--render-backend", choices=["ovrtx", "remote", "warp"], default="remote")
    parser.add_argument("--vlm-backend", help="Override Physics Agent VLM backend, such as openai or nim")
    parser.add_argument("--vlm-model", help="Override Physics Agent VLM model")
    parser.add_argument("--collision-approx", default="convexHull")
    parser.add_argument("--dry-run", action="store_true", help="Show the Physics Agent plan without executing")
    parser.add_argument("--clean", action="store_true", help="Pass --clean to physics-agent run")
    parser.add_argument("--resume", action="store_true", help="Pass --resume to physics-agent run")
    parser.add_argument("--skip", help="Comma-separated Physics Agent steps to skip")
    parser.add_argument("--only", help="Comma-separated Physics Agent steps to run exclusively")
    parser.add_argument("--summary-json", type=Path, help="Optional path for bridge summary JSON")
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)
    config_path = _write_config(
        input_usd=args.input_usd,
        output_dir=args.output_dir,
        content_agents_root=args.content_agents_root,
        render_backend=args.render_backend,
        vlm_backend=args.vlm_backend,
        vlm_model=args.vlm_model,
        collision_approx=args.collision_approx,
    )
    outputs = _expected_outputs(args.input_usd, args.output_dir)

    command = [str(args.physics_agent), "run", str(config_path)]
    if args.dry_run:
        command.append("--dry-run")
    if args.clean:
        command.append("--clean")
    if args.resume:
        command.append("--resume")
    if args.skip:
        command.extend(["--skip", args.skip])
    if args.only:
        command.extend(["--only", args.only])

    completed = subprocess.run(command, cwd=str(args.content_agents_root), check=False)
    payload = {
        "input_usd": str(args.input_usd),
        "config_path": str(config_path),
        "command": command,
        "returncode": completed.returncode,
        "outputs": outputs,
    }
    summary_path = args.summary_json or (args.output_dir / f"{_safe_session_id(args.input_usd.stem)}.physics_agent.summary.json")
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
    print(summary_path)
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
